up:
	docker-compose up

down:
	docker-compose down

tidy:
	cd src/core && go mod tidy
	cd src/adapter && go mod tidy
	cd src/migration && go mod tidy
	cd src/worker && go mod tidy
	cd src/pancake && go mod tidy
	cd src/internal && go mod tidy
	cd src/public && go mod tidy

test:
	cd src/core && go mod tidy && go test ./...
	cd src/adapter && go mod tidy && go test ./...
	cd src/migration && go mod tidy && go test ./...
	cd src/pancake && go mod tidy && go test ./...
	cd src/internal && go mod tidy && go test ./...
	cd src/public && go mod tidy && go test ./...
	cd src/worker && go mod tidy && go test ./...

swagger-public:
	cd src/public && swag init --parseDependency --parseDepth=3

swagger-worker:
	cd src/worker && swag init --parseDependency --parseDepth=3

swagger-pancake:
	cd src/pancake && swag init --parseDependency --parseDepth=3

swagger-internal:
	cd src/internal && swag init --parseDependency --parseDepth=3

love:
	cd src/core && gosec ./...
	cd src/adapter && gosec ./...
	cd src/migration && gosec ./...
	cd src/pancake && gosec ./...
	cd src/internal && gosec ./...
	cd src/public && gosec ./...
	cd src/worker && gosec ./...

vet:
	cd src/core && go vet ./...  && staticcheck ./...
	cd src/adapter && go vet ./... && staticcheck ./...
	cd src/migration && go vet ./... && staticcheck ./...
	cd src/pancake && go vet ./... && staticcheck ./...
	cd src/internal && go vet ./... && staticcheck ./...
	cd src/public && go vet ./... && staticcheck ./...
	cd src/worker && go vet ./... && staticcheck ./...
