steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '${IMAGE_NAME}:${IMAGE_TAG}',
      '--file=${DOCKER_FILE}',
      '--build-arg', 'GITLAB_USER=${GITLAB_USER}',
      '--build-arg', 'GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}',
      '--build-arg', 'BUILD_COMMIT_HASH=${BUILD_COMMIT_HASH}',
      '--build-arg', 'BUILD_TIME=${BUILD_TIME}',
      '--build-arg', 'MODULE=${MODULE}',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ "push", "${IMAGE_NAME}:${IMAGE_TAG}" ]
options:
  logging: CLOUD_LOGGING_ONLY