apiVersion: batch/v1
kind: Job
metadata:
  name: $SERVICE_NAME
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: $SERVICE_NAME
          image: $IMAGE_NAME:$IMAGE_TAG
          envFrom:
            - configMapRef:
                name: $SERVICE_NAME
            - secretRef:
                name: $SERVICE_NAME
      restartPolicy: Never
      imagePullSecrets:
        - name: docker-image-pull-secret
