app:
  datasource:
    driver: mysql
    host: localhost
    port: 3306
    database: campaigns_manager_autogen
    username: root
    password: secret
    params: parseTime=true&multiStatements=true
    migrationSource: file://migrations
