app:
  datasource:
    driver: mysql
    host: mysql-main.int.position.exchange
    port: 3306
    database: campaigns_manager_autogen
    username: campaigns_manager_autogen
    params: parseTime=true&multiStatements=true
    migrationSource: file://migrations
