app: 
  datasource:
    driver: mysql
    host: mysql-main.int.position.exchange
    port: 3306
    database: campaigns_manager_autogen
    username: campaigns_manager_autogen
    params: parseTime=true
  redis:
    host: redis-main.int.position.exchange
    port: 6379
    database: 0
  kafka:
    bootstrapServers: kafka-main-01.int.position.exchange:9092,kafka-main-02.int.position.exchange:9092,kafka-main-03.int.position.exchange:9092
    clientId: campaigns_manager_autogen
    consumer:
      handlerMappings:
        LockedSlotConsumer:
          topic: domain.sub
          groupId: campaigns_manager_autogen.public.locked-slot
          enable: true
  cron:
    jobs:
      LockedSlotJob:
        expression: "@every 5s"

