app:
  datasource:
    driver: mysql
    host: mysql-main.int.position.exchange
    port: 3306
    database: campaigns_manager
    username: campaigns_manager
    params: parseTime=true
    migrationSource: file://migrations
  redis:
    host: redis-main.int.position.exchange
    port: 6379
    database: 0
  emitter:
    host: redis-web-socket.int.position.exchange
    port: 6379
    database: 0
  kafka:
    bootstrapServers: kafka-main-01.int.position.exchange:9092,kafka-main-02.int.position.exchange:9092,kafka-main-03.int.position.exchange:9092
    clientId: campaigns-manager
    producer:
      eventMappings:
    consumer:
      handlerMappings:

