app:
  swagger.enabled: true
  datasource:
    driver: mysql
    host: mysql-main.int.nonprodposi.com
    port: 3306
    database: campaigns_manager_qc
    username: campaigns_manager_qc
    params: parseTime=true
  kafka:
    bootstrapServers: kafka-main-01.int.nonprodposi.com:9092,kafka-main-02.int.nonprodposi.com:9092,kafka-main-03.int.nonprodposi.com:9092
    clientId: campaigns-manager-qc
    consumer:
      handlerMappings:
        LockedSlotConsumer:
          topic: source.locked-slot.qc
          groupId: campaigns-manager.public.locked-slot.qc
          enable: true
  cron:
    jobs:
      LockedSlotJob:
        expression: "@every 5s"

