app:
  swagger.enabled: true
  datasource:
    driver: mysql
    host: mysql-main.int.nonprodposi.com
    port: 3306
    database: campaigns_manager_qc
    username: campaigns_manager_qc
    params: parseTime=true
  cron:
    jobs:
      LockedSlotJob:
        expression: "@every 5s"

