app:
  logging:
    JsonOutputMode: false

  repo: gitlab.com/technixo/backend/campaigns_manager_autogen
  path: ".."
  modules:
    - name: "public"
      enabledFeatures:
        swagger: true
        mysql: true
        job: true
        consumer: true
        redis: true
        http-client: true
      options:
        consumers:
          - name: "locked-slot"
            topic: "domain.sub"
        jobs:
          - name: "locked-slot"
        controllers:
          - name: "campaign"
            path: "campaigns"
            methods:
              getAll: true
              get: true
              create: true
              update: true
          - name: "locked-slot"
            path: "locked-slots"
            methods:
              getAll: true
              get: true
              create: true
              update: true