app:
  logging:
    JsonOutputMode: false

  repo: gitlab.com/technixo/backend/campaigns_manager_autogen
  path: ".."
  modules:
    public:
      enabledFeatures:
        swagger: true
        mysql: true
        job: true
        consumer: true
        redis: true
      options:
        consumers:
          locked-slot:
            topic: "domain.sub"
        jobs:
          locked-slot: true
        controllers:
          campaign:
            path: "campaigns"
            methods:
              getAll: true
              get: true
              create: true
              update: true
          locked-slot:
            path: "locked-slots"
            methods:
              getAll: true
              get: true
              create: true
              update: true