app:
  logging:
    JsonOutputMode: false

  repo: gitlab.com/technixo/backend/campaigns-manager
  path: ".."
  modules:
    public:
      enabledFeatures:
        swagger: true
        mysql: true
        job: true
        consumer: true
      options:
        consumers:
          locked-slot: true
        jobs:
          locked-slot: true
        controllers:
          campaign:
            path: "campaigns"
            methods:
              getAll: true
              get: true
              create: true
              update: true
          locked-slot:
            path: "locked-slots"
            methods:
              getAll: true
              get: true
              create: true
              update: true