app:
  logging:
    JsonOutputMode: false

  repo: gitlab.com/technixo/backend/campaigns-manager
  path: ".."
  modules:
    public:
      enabledFeatures:
        swagger: .
        mysql: .
        job: .
      options:
        jobs:
          locked-slot: .
        controllers:
          campaign:
            path: "campaigns"
            methods:
              getAll: .
              get: .
              create: .
              update: .
          locked-slot:
            path: "locked-slots"
            methods:
              getAll: .
              get: .
              create: .
              update: .