app:
  logging:
    JsonOutputMode: false

  repo: gitlab.com/technixo/backend/campaigns-manager
  path: ".."
  modules:
    public:
      enabledFeatures:
        swagger: .
        mysql: .
      options:
        controllers:
          campaign:
            path: "campaigns"
            methods:
              getAll: .