// Code generated by cli. DO NOT EDIT.

package bootstrap

import (
	"gitlab.com/golibs-starter/golib"
	golibdata "gitlab.com/golibs-starter/golib-data"
	golibgin "gitlab.com/golibs-starter/golib-gin"
	"gitlab.com/golibs-starter/golib-message-bus"
	"gitlab.com/technixo/backend/campaigns_manager/public/routers"
	"gitlab.com/technixo/golib-emitter"
	"go.uber.org/fx"
)

func AutoConfig() fx.Option {
	return fx.Options(
		golib.AppOpt(),
		golib.PropertiesOpt(),
		golib.LoggingOpt(),

		golib.EventOpt(),

		golib.BuildInfoOpt(Version, CommitHash, BuildTime),
		golib.ActuatorEndpointOpt(),
		golibgin.GinHttpServerOpt(),
		fx.Invoke(routers.RegisterHandlers),
		fx.Invoke(routers.RegisterGinRouters),
		// Provide all application properties

		// Provide datasource auto config
		golibdata.DatasourceOpt(),
		golibemitter.EnableEmitter(),
		golibmsg.KafkaConsumerOpt(),
		// Provide port's implements

		// Provide controllers, these controllers will be used
		// when register router was invoked

		// Graceful shutdown.
		// OnStop hooks will run in reverse order.
		// golib.OnStopEventOpt() MUST be first
		golib.OnStopEventOpt(),
		golibgin.OnStopHttpServerOpt(),
		golibmsg.OnStopConsumerOpt(),
	)
}
