// Code generated by cli. DO NOT EDIT.

package bootstrap

import (
	"gitlab.com/technixo/backend/campaigns-manager/core/usecases"
	"gitlab.com/technixo/backend/campaigns-manager/public/controllers"
	"gitlab.com/technixo/backend/campaigns-manager/public/services"
	"go.uber.org/fx"
)

func GeneratedModule() fx.Option {
	return fx.Options(
		fx.Provide(usecases.NewGetCampaignUsecase),
		fx.Provide(usecases.NewCreateCampaignUsecase),
		fx.Provide(usecases.NewUpdateCampaignUsecase),
		fx.Provide(services.NewCampaignService),
		fx.Provide(controllers.NewCampaignController),
	)
}
